data = [
        {"ID" : 1, "Name" : "Всероссийская олимпиада по русскому языку",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType": "Всероссийская олимпиада", "Class": ["9", "10", "11"],
         "Stage": 3, "OlympiadDate": "13.01.2020", "SchoolYear": 2020,
         "Theme": "Русский язык", "University":["МИФИ"]},

        {"ID": 2, "Name": "Всероссийская олимпиада по информатике",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["9", "10", "11"], "Stage": 3,
         "OlympiadDate": "16.01.2020, 18.01.2020", "SchoolYear": 2020,
         "Theme": "Информатика",
         "University": ["МИФИ", "МФТИ", "МГУ"]},

        {"ID": 3,"Name": "Всероссийская астрономическая олимпиада",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType":"Всероссийская олимпиада","Class": ["9", "10", "11"],
         "Stage": 3, "OlympiadDate": "20.01.2020", "SchoolYear": 2020,
         "Theme": "Астрономия", "University":["МИФИ", "МФТИ"]},

        {"ID": 4, "Name": "Всероссийская олимпиада по физике",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType": "Всероссийская олимпиада", "Class": ["9", "10", "11"],
         "Stage": 3, "OlympiadDate": "23.01.2020, 25.01.2020",
         "SchoolYear": 2020,"Theme": "Физика", "University": ["МИФИ", "МФТИ"]},

        {"ID": 5, "Name": "Всероссийская олимпиада по химии",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType": "Всероссийская олимпиада", "Class": ["9", "10", "11"],
         "Stage": 3, "OlympiadDate": "30.01.2020, 31.01.2020",
         "SchoolYear": 2020, "Theme": "Химия",
         "University": ["МИФИ", "МФТИ"]},

        {"ID": 6,"Name": "Всероссийская олимпиада по математике",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["9", "10", "11"], "Stage": 3, "OlympiadDate": "03.02.2020, 04.02.2020",
         "SchoolYear": 2020, "Theme": "Математика",
         "University": ["МИФИ", "МФТИ", "МГУ"]},

        {"ID": 7, "Name":"Всероссийская олимпиада по экономике",
         "WebSite": "vos.olimpiada.ru/2020/region",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["9", "10", "11"], "Stage": 3,
         "OlympiadDate": "15.02.2020", "SchoolYear": 2020,
         "Theme": "Экономика",
         "University": ["МИФИ", "МФТИ"]},

        {"ID": 8, "Name": "Турнир имени М.В. Ломоносова",
         "WebSite": "turlom.olimpiada.ru",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["6", "7", "8", "9", "10", "11"], "Stage": 3,
         "OlympiadDate": "01.03.2020","SchoolYear": 2020,
         "Theme": "Астрономия",
         "University": ["МГТУ им. Н.Э.Баумана", "МГУ"]},

        {"ID": 10, "Name": "Турнир имени М.В. Ломоносова",
         "WebSite": "turlom.olimpiada.ru",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["6", "7", "8", "9", "10", "11"], "Stage": 2,
         "OlympiadDate": "01.03.2020", "SchoolYear": 2020,
         "Theme": "Математика",
         "University": ["МГТУ им. Н.Э.Баумана", "МГУ"]},

        {"ID": 11, "Name": "Турнир имени М.В. Ломоносова",
         "WebSite": "turlom.olimpiada.ru",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["6", "7", "8", "9", "10", "11"], "Stage": 2,
         "OlympiadDate": "01.03.2020", "SchoolYear": 2020,
         "Theme": "Физика",
         "University": ["МГТУ им. Н.Э.Баумана", "МГУ"]},

        {"ID": 12, "Name": "Турнир имени М.В. Ломоносова",
         "WebSite": "turlom.olimpiada.ru",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["6", "7", "8", "9", "10", "11"], "Stage": 2,
         "OlympiadDate": "01.03.2020", "SchoolYear": 2020,
         "Theme": "Химия",
         "University": ["МГТУ им. Н.Э.Баумана", "МГУ"]},

        {"ID": 13, "Name": "Отраслевая олимпиада школьников «Газпром»",
         "WebSite": "olympiad.gazprom.ru",
         "OlympiadType":"Всероссийская олимпиада",
         "Class": ["9", "10", "11"], "Stage": 3, "OlympiadDate": "01.03.2020",
         "SchoolYear": 2020, "Theme": "Химия",
         "University": ["МГТУ им. Н.Э.Баумана"]},

        {"ID": 14, "Name": "Отраслевая физико-математическая олимпиада школьников «Росатом»",
         "WebSite": "admission.mephi.ru/olympiads/rosatom",
         "OlympiadType": "Всероссийская олимпиада",
         "Class": ["7", "8", "9", "10", "11"], "Stage": 1,
         "OlympiadDate": "01.03.2020", "SchoolYear": 2020, "Theme": "Физика",
         "University": ["МИФИ","МГТУ им. Н.Э.Баумана"]},

        {"ID": 15, "Name":"Отраслевая физико-математическая олимпиада школьников «Росатом»",
         "WebSite": "admission.mephi.ru/olympiads/rosatom",
         "OlympiadType": "Всероссийская олимпиада",
         "Class":["7", "8", "9", "10", "11"],
         "Stage": 2, "OlympiadDate": "01.03.2020",
         "SchoolYear": 2020, "Theme": "Математика",
         "University": ["МИФИ", "МГТУ им. Н.Э.Баумана"]},

        {"ID": 16, "Name": "Олимпиада «ФИЗТЕХ»",
         "WebSite": "olymp.mipt.ru",
         "OlympiadType": "Всероссийская олимпиада", "Class": ["9", "10", "11"],
         "Stage": 2, "OlympiadDate": "01.03.2020", "SchoolYear": 2020,
         "Theme": "Математика",
         "University": ["МГТУ им. Н.Э.Баумана"]},

        {"ID": 17, "Name": "Олимпиада «ФИЗТЕХ»",
         "WebSite": "olymp.mipt.ru",
         "OlympiadType":"Всероссийская олимпиада",
         "Class": ["9", "10", "11"], "Stage": 2,
         "OlympiadDate": "01.03.2020",
         "SchoolYear": 2020, "Theme": "Физика",
         "University": ["МГТУ им. Н.Э.Баумана", "МГУ"]}]